---
title: "test SLAM functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SLAM)
library(dplyr)
```

## Test merge_diftime

```{r}
# Example Merging clostest NMR to Glucose --------------------------------------

# Checkout data --------------------------------------------------------------
# Checkout census
head(data_SLAM_census)

# Checkout glucose
head(data_SLAM_gluc)

# Checkout nmr
head(data_SLAM_nmr)

# Create gluc ----------------------------------------------------------------
# join glucose and census for dob and other infor
gluc <- dplyr::left_join(data_SLAM_gluc, data_SLAM_census, by = "idno")
# drop useless vars
gluc <- dplyr::select(gluc, -c(lact, cohort, animal_id, tag, taghistory, cage, eartag, name, X))
# create age for merging and format data so it makes sense
gluc <- dplyr::mutate(gluc,
                      age_wk = difftime(date, dob, units = "weeks"),
                      date = as.Date(date, "%m%d%Y")
)

# Create nmr -----------------------------------------------------------------
# join nmr with census for dob and other info
nmr <- dplyr::left_join(data_SLAM_nmr, data_SLAM_census, by = "idno")
# drop useless columns
nmr <- dplyr::select(nmr, -c(cohort, animal_id, tag, taghistory, cage, eartag, name, X))
# create age for merging and format data so it makes sense
nmr <- dplyr::mutate(nmr,
                     age_wk = difftime(date, dob, units = "weeks"),
                     date = as.Date(date, "%m%d%Y")
)

# Use merge_diftime ----------------------------------------------------------
gluc_nmr <- merge_diftime(
  data1 = gluc,
  data2 = nmr,
  id = "idno",
  age = "age_wk",
  vars = c("bw", "lean", "fluid", "fat"),
  clean_vars = FALSE)

# Checkout results
head(gluc_nmr)

# test ------------------------------------------------------------------------
  data1 <- gluc
  data2 <- nmr
  id <- "idno"
  age <- "age_wk"
  vars <- c("bw", "lean", "fluid", "fat")
  suffixes <- c(".1", ".2")
  clean_vars <- "both"
  threshold <- Inf
  where <- "both"


merge_diftime <- function(data1, data2, id, age, threshold = Inf, vars = NULL, where = "both", suffixes = c(".1", ".2"), clean_vars = TRUE) {
  
  # prep data1 and data2 -------------------------------------------------------
  # manually add suffixes so easy to identify which column came from which dataframe
  names(data1) <- paste0(names(data1), suffixes[1])
  names(data2) <- paste0(names(data2), suffixes[2])

  # create id and age vars if length id = 1 or 2 -------------------------------
  # do this for consistency of function regardless of age or id input
  # create corresponding id vars
  if (length(id) == 1) {
    id1 <- paste0(id, suffixes[1])
    id2 <- paste0(id, suffixes[2])
  } else if (length(id) == 2) {
    id1 <- paste0(id[1], suffixes[1])
    id2 <- paste0(id[2], suffixes[1])
  } else {
    stop("id must be length 1 or 2")
  }

  # create corresponding age vars
  if (length(age) == 1) {
    age1 <- paste0(age, suffixes[1])
    age2 <- paste0(age, suffixes[2])
  } else if (length(age) == 2) {
    age1 <- paste0(age[1], suffixes[1])
    age2 <- paste0(age[2], suffixes[1])
  } else {
    stop("age must be length 1 or 2")
  }

  # if vars specified ----------------------------------------------------------
  # if vars are specified ensure complete cases for those vars
  if (is.null(vars)) {
    data2 <- data2
  } else if (!is.null(vars)) {
    vars_suf <- paste0(vars, suffixes[2])
    data2 <- data2[complete.cases(data2[vars_suf]), ]
  }

  # merge and create dif -------------------------------------------------------
  data_m <- merge(data1, data2, by.x = id1, by.y = id2, all.x = TRUE, suffixes = suffixes)

  # dif tells use time difference and direction
  data_m$dif <- data_m[[age2]] - data_m[[age1]]

  # look for closest date ------------------------------------------------------
  # where to check for closest date
  if (where == "both") {
    data_m <- data_m[order(data_m[[id1]], abs(data_m$dif)), , drop = FALSE]
    df_dups <- data_m[c(id1, age1)]
    data_m <- data_m[!duplicated(df_dups), , drop = FALSE]
    # threshold
    data2_cols <- names(data_m)[grepl(paste0(suffixes[2], "$"), names(data_m))]
    data2_cols <- data2_cols[sapply(data2_cols, function(col) class(data_m[[col]])) != "Date"]
    data_m[, data2_cols] <- lapply(data2_cols, function(name) {
      if(class(data_m[,name])!="Date"){
        ifelse(abs(data_m$dif) > threshold, NA, data_m[, name])
      } else{}
    })
  } else if (where == "before") {
    data_m <- data_m[data_m$dif <= 0, ]
    data_m <- data_m[order(data_m[[id1]], -1 * data_m$dif), , drop = FALSE]
    df_dups <- data_m[c(id1, age1)]
    data_m <- data_m[!duplicated(df_dups), , drop = FALSE]
    # threshold
    data2_cols <- names(data_m)[grepl(paste0(suffixes[2], "$"), names(data_m))]
    data2_cols <- data2_cols[sapply(data2_cols, function(col) class(data_m[[col]])) != "Date"]
    data_m[, data2_cols] <- lapply(data2_cols, function(name) {
      ifelse(data_m$dif * -1 > threshold, NA, data_m[, name])
    })
  } else if (where == "after") {
    data_m <- data_m[data_m$dif >= 0, ]
    data_m <- data_m[order(data_m[[id1]], data_m$dif), , drop = FALSE]
    df_dups <- data_m[c(id1, age1)]
    data_m <- data_m[!duplicated(df_dups), , drop = FALSE]
    # threshold
    data2_cols <- names(data_m)[grepl(paste0(suffixes[2], "$"), names(data_m))]
    data2_cols <- data2_cols[sapply(data2_cols, function(col) class(data_m[[col]])) != "Date"]
    data_m[, data2_cols] <- lapply(data2_cols, function(name) {
      ifelse(data_m$dif > threshold, NA, data_m[, name])
    })
  } else {
    stop("where must be both, before, or after")
  }
  
  # clean vars -----------------------------------------------------------------
  if (isTRUE(clean_vars)) {
    suf1_regx <- paste0(suffixes[1], "$")
    suf2_regx <- paste0(suffixes[2], "$")
    col1 <- names(data_m)[grepl(suf1_regx, names(data_m))]
    col2 <- names(data_m)[grepl(suf2_regx, names(data_m))]

    col1_clean <- gsub(suf1_regx, replacement = "", x = col1)
    col2_clean <- gsub(suf2_regx, replacement = "", x = col2)

    if (length(age) == 1) {
      col1_clean <- gsub(age, replacement = age1, x = col1_clean)
      col2_clean <- gsub(age, replacement = age2, x = col2_clean)
    } else if (length(age) == 2) {
      col1_clean <- gsub(age[1], replacement = age1, x = col1_clean)
      col2_clean <- gsub(age[2], replacement = age2, x = col2_clean)
    }

    var_keep <- col2[!col2_clean %in% col1_clean]
    var_keep <- c(col1, var_keep, "dif")

    data_m <- data_m[, var_keep]
    names(data_m)[names(data_m) %in% col1] <- col1_clean
  }

  data_m
}

```

## Test add_delta

```{r add_delta}
# test ---------------------------------
data <- data_SLAM_nmr %>%
  dplyr::left_join(data_SLAM_census, by = "idno") 

data <- data[data$cohort %in% c(1,2,3,4,5,6), ]
cols <- c("bw","fat")
id <- "idno"
type <- "lag"
fill <- 0
n <- 1L
time <- "date"
prefix <- paste("delta", type, n, sep = "_")

add_delta_test <-function(data, cols, id, time, fill = 0, n = 1L, type = "lag", prefix = paste("delta", type, n, sep = "_")){
  
  # convert fill to numeric
  fill <- as.numeric(fill)
  # convert data to datatable
  dt <- data.table::data.table(data)

  # loop through cols ----------------------------------------------------------
  for(col in cols){
    # calculate deltas for variable defined by col -----------------------------
    # delta variable name
    col_delta <- paste(prefix, col, sep = "_")
    # na varialbe name
    col_na <- paste(col, "na", sep = "_")
    
    # data table chain ---------------------------------------------------------
    # create col_na that is true if col is NA and false otherwise
    dt <- dt[, (col_na) := lapply(.SD, is.na), .SDcols = col 
    # order dt by time so that rolling differences are taken properly
                  ][order(dt[[time]])
    # create delta variable using n and type arguments specified in function call.
    # the dt is grouped by id and col_na so that delta calculation will "skip"
    # dates when there is NAs
                    ][, (col_delta) := .SD - data.table::shift(x = .SD, n = n, fill = NA, type = type), keyby = c(id, col_na), .SDcols = col]
    # if there are NA's in col_delta and no NAs in col, we know that the NA
    # in col_delta is from lag window. We want to replace these NA's. However,
    # any NA's in col_delta from due to an NA in col, we want to leave these NA.
    dt <- dt[is.na(dt[[col_delta]]) & !dt[[col_na]], (col_delta) := (fill)
    # Drop the na column
             ][, (col_na) := NULL]
                      
  }
  # ----------------------------------------------------------------------------

  # reorder by id and time because currently order by time, id, and col_na
  dt <- data.table::setorderv(x = dt, col = c(id, time))
  # convert data.table to dataframe
  data <-as.data.frame(dt)
  
  #return data
  data
}


data <- add_delta(data = data, cols = c("bw", "fat", "lean", "fluid"), id = id, time = time, fill = 0)
```



